factors1

diff --git a/factors b/factors
--- a/factors
+++ b/factors
@@ -1,34 +1,32 @@
 #!/usr/bin/env bash
 
 check_factor() {
-    if [ $# -ne 3 ]; then
-        args=("$@")
-        count=0
-        num2=1
-        for a in "${args[@]}"; do
-            if [ $count -gt 1 ]; then
-                num2=$(($a*$num2)) 
-            fi
-            count=$((count + 1))
-        done
-    else
-        num2=$3
+    if [ $# -ne 2 ]; then
+        echo "Invalid number of arguments in check_factor function"
+        exit 1
     fi
 
-    num1=$2
-    num=$(echo "$1" | tr ':' '=')
+    num1=$1
+    num2=$2
 
-    result=$((num2 > num1 ? 1 : 0))
-    if [ $result -eq 1 ]; then
-        numcp=$num1
-        num1=$num2
-        num2=$numcp
-    fi
-
-    echo "$num$num1*$num2"  
+    echo "$num1=$num2*$(($num1 / $num2))"
 }
 
-while read -r line; do
-    result=$(check_factor "$line")
-    check_factor $result  
-done < "$1"
+factorize_number() {
+    local number=$1
+    # Implement an efficient factorization algorithm here
+    # Update num1 and num2 accordingly
+    num1=...
+    num2=...
+    check_factor $num1 $num2
+}
+
+if [ $# -ne 1 ]; then
+    echo 'Usage: factors <file>'
+    exit 1
+else
+    while read -r number; do
+        factorize_number "$number"
+    done < "$1"
+fi
+
